name: test
on:
  issue_comment:
    types: [created]
jobs:
  create_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        go-version:
          - "1.20"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: ^/test\s*(.*?)\s*$
      - name: Create comment
        id: create_comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            目标为 ${{ steps.regex-match.outputs.group1 }} 的自动测试启动了。
            - 你可以在 [这里](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) 找到测试过程和结果。
            - 由 [test-action](https://github.com/foxwhite25/megaCrawler/blob/master/.github/workflows/test.yml) 创建。
      - name: Setup Go
        uses: actions/setup-go@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set ENV
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: echo "TARGET=${{ steps.regex-match.outputs.group1 }}" >> $GITHUB_ENV
      - name: Install dependencies
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: go get .
      - name: Test with Go
        id: test
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: go test
      - name: Get File into OUTPUT
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          echo 'RESULT<<EOF' >> $GITHUB_ENV
          cat table.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Upload Go log
        uses: actions/upload-artifact@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          name: Go-log-${{ matrix.go-version }}
          path: ./log/debug.jsonl
      - name: Update comment
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.create_comment.outputs.comment-id }}
          reactions: rocket
          body: |         
            ## Edit: 本次运行已完成！
            你可以在 [这里](https://foxwhite25.github.io/log-viewer/?auth=${{ secrets.VIEW_ONLY }}&run_id=${{ github.run_id }}) 看到 Log 。
            或者直接在下方查看简单描述。
            ```
            ${{ env.RESULT }}
            ```
